/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/ehOa2oT3OFd
 */
import Link from "next/link"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { CardTitle, CardHeader, CardContent, Card } from "@/components/ui/card"

export function home() {
  return (
    <div className="flex flex-col h-screen font-sans bg-[#ffffff] text-[#000000]">
      <header className="flex items-center h-16 px-4 border-b shrink-0">
        <nav className="flex flex-row items-center justify-between w-full gap-6 text-lg font-medium md:gap-5 md:text-sm lg:gap-6">
          <Link className="flex items-center gap-2 text-lg font-semibold md:text-base" href="#">
            <Package2Icon className="w-6 h-6" />
            <span>Troulette</span>
          </Link>
          <div className="flex items-center gap-4">
            <Button className="rounded-full" size="icon" variant="ghost">
              <UserIcon className="w-4 h-4" />
              <span className="sr-only">Profile</span>
            </Button>
          </div>
        </nav>
      </header>
      <main className="flex flex-1 flex-col gap-4 md:gap-8 md:p-10">
        <div className="flex flex-row gap-4 justify-center">
          <form className="flex-1 sm:flex-initial">
            <div className="relative">
              <label className="block text-sm font-medium text-gray-700">Departing:</label>
              <Input className="sm:w-[300px] md:w-[200px] lg:w-[300px]" placeholder="Departing from..." type="text" />
            </div>
          </form>
          <form className="flex-1 sm:flex-initial">
            <div className="relative">
              <label className="block text-sm font-medium text-gray-700">From:</label>
              <CalendarDaysIcon className="absolute left-2.5 top-6 h-4 w-4 text-gray-500 dark:text-gray-400" />
              <Input className="pl-8 sm:w-[300px] md:w-[200px] lg:w-[300px]" placeholder="Start date..." type="date" />
            </div>
          </form>
          <form className="flex-1 sm:flex-initial">
            <div className="relative">
              <label className="block text-sm font-medium text-gray-700">To:</label>
              <CalendarDaysIcon className="absolute left-2.5 top-6 h-4 w-4 text-gray-500 dark:text-gray-400" />
              <Input className="pl-8 sm:w-[300px] md:w-[200px] lg:w-[300px]" placeholder="End date..." type="date" />
            </div>
          </form>
        </div>
        <Button className="self-center border border-gray-300 bg-[#ed4264] text-[#ffffff] py-8 px-8 text-lg">
          Troulette
        </Button>
        <div className="flex justify-center gap-8">
          <Card className="hover:bg-gray-200 transition-colors duration-200">
            <CardHeader className="flex flex-row items-center justify-between pb-2 space-y-0">
              <CardTitle className="text-sm font-medium">
                Flight
                <br />
                to New York{"\n                          "}
              </CardTitle>
              <PlaneIcon className="w-4 h-4 text-gray-500 dark:text-gray-400" />
            </CardHeader>
            <CardContent>
              <div className="text-2xl font-bold">$123</div>
              <p className="text-xs text-gray-500 dark:text-gray-400">Lowest price found</p>
            </CardContent>
          </Card>
          <div className="flex items-center justify-center text-3xl font-bold">+</div>
          <Card className="hover:bg-gray-200 transition-colors duration-200">
            <CardHeader className="flex flex-row items-center justify-between pb-2 space-y-0">
              <CardTitle className="text-sm font-medium">
                Hotel
                <br />
                in New York{"\n                          "}
              </CardTitle>
              <HotelIcon className="w-4 h-4 text-gray-500 dark:text-gray-400" />
            </CardHeader>
            <CardContent>
              <div className="text-2xl font-bold">$456</div>
              <p className="text-xs text-gray-500 dark:text-gray-400">Lowest price found</p>
            </CardContent>
          </Card>
          <div className="flex items-center justify-center text-3xl font-bold">+</div>
          <Card className="hover:bg-gray-200 transition-colors duration-200">
            <CardHeader className="flex flex-row items-center justify-between pb-2 space-y-0">
              <CardTitle className="text-sm font-medium">
                Rental Car
                <br />
                in New York{"\n                          "}
              </CardTitle>
              <CarIcon className="w-4 h-4 text-gray-500 dark:text-gray-400" />
            </CardHeader>
            <CardContent>
              <div className="text-2xl font-bold">$789</div>
              <p className="text-xs text-gray-500 dark:text-gray-400">Lowest price found</p>
            </CardContent>
          </Card>
          <div className="flex items-center justify-center text-3xl font-bold">=</div>
          <Card>
            <CardHeader className="flex flex-row items-center justify-between pb-2 space-y-0">
              <CardTitle className="text-sm font-medium">Total Vacation Price</CardTitle>
              <DollarSignIcon className="w-4 h-4 text-gray-500 dark:text-gray-400" />
            </CardHeader>
            <CardContent>
              <div className="text-2xl font-bold">$1368</div>
              <p className="text-xs text-gray-500 dark:text-gray-400">Combined price</p>
            </CardContent>
          </Card>
        </div>
        <div className="flex flex-col items-center gap-4 mt-8">
          <p className="text-center text-gray-600">
            Not vibing with the current scene? Craving results that scream &lsquo;you&rsquo;? Let&apos;s get personal! ✨🔍
          </p>
          <Button className="border border-gray-300 bg-[#ed4264] text-[#ffffff] py-2 px-4 text-lg">Sign Up</Button>
          <p className="text-center text-gray-600">
            Score a premium account for just a buck a month
            <br /> or go all-in for the year at a cool $10 upfront! 🚀💸
          </p>
        </div>
      </main>
      <footer className="flex items-center justify-center h-16 px-4 border-t text-sm text-gray-500 dark:text-gray-400">
        <span>© 2024 Troulette. All rights reserved. | </span>
        <Link className="ml-2" href="#">
          Privacy Policy
        </Link>
        <span className="mx-2">|</span>
        <Link className="mr-2" href="#">
          Terms of Service
        </Link>
      </footer>
    </div>
  )
}


import React from 'react';

interface Package2IconProps {
  className?: string; // You can include other props if needed
}

function Package2Icon(props: Package2IconProps) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M3 9h18v10a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V9Z" />
      <path d="m3 9 2.45-4.9A2 2 0 0 1 7.24 3h9.52a2 2 0 0 1 1.8 1.1L21 9" />
      <path d="M12 3v6" />
    </svg>
  );
}

export default Package2Icon;


interface UserIconProps {
  className?: string; // You can include other props if needed
}

function UserIcon(props: UserIconProps) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M19 21v-2a4 4 0 0 0-4-4H9a4 4 0 0 0-4 4v2" />
      <circle cx="12" cy="7" r="4" />
    </svg>
  );
}


interface CalendarDaysIconProps {
  className?: string; // You can include other props if needed
}

function CalendarDaysIcon(props: CalendarDaysIconProps) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <rect width="18" height="18" x="3" y="4" rx="2" ry="2" />
      <line x1="16" x2="16" y1="2" y2="6" />
      <line x1="8" x2="8" y1="2" y2="6" />
      <line x1="3" x2="21" y1="10" y2="10" />
      <path d="M8 14h.01" />
      <path d="M12 14h.01" />
      <path d="M16 14h.01" />
      <path d="M8 18h.01" />
      <path d="M12 18h.01" />
      <path d="M16 18h.01" />
    </svg>
  );
}


interface PlaneIconProps {
  className?: string; // You can include other props if needed
}

function PlaneIcon(props: PlaneIconProps) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M17.8 19.2 16 11l3.5-3.5C21 6 21.5 4 21 3c-1-.5-3 0-4.5 1.5L13 8 4.8 6.2c-.5-.1-.9.1-1.1.5l-.3.5c-.2.5-.1 1 .3 1.3L9 12l-2 3H4l-1 1 3 2 2 3 1-1v-3l3-2 3.5 5.3c.3.4.8.5 1.3.3l.5-.2c.4-.3.6-.7.5-1.2z" />
    </svg>
  );
}


interface HotelIconProps {
  className?: string; // You can include other props if needed
}

function HotelIcon(props: HotelIconProps) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M18 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V4a2 2 0 0 0-2-2Z" />
      <path d="m9 16 .348-.24c1.465-1.013 3.84-1.013 5.304 0L15 16" />
      <path d="M8 7h.01" />
      <path d="M16 7h.01" />
      <path d="M12 7h.01" />
      <path d="M12 11h.01" />
      <path d="M16 11h.01" />
      <path d="M8 11h.01" />
      <path d="M10 22v-6.5m4 0V22" />
    </svg>
  );
}


interface CarIconProps {
  className?: string; // You can include other props if needed
}

function CarIcon(props: CarIconProps) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M19 17h2c.6 0 1-.4 1-1v-3c0-.9-.7-1.7-1.5-1.9C18.7 10.6 16 10 16 10s-1.3-1.4-2.2-2.3c-.5-.4-1.1-.7-1.8-.7H5c-.6 0-1.1.4-1.4.9l-1.4 2.9A3.7 3.7 0 0 0 2 12v4c0 .6.4 1 1 1h2" />
      <circle cx="7" cy="17" r="2" />
      <path d="M9 17h6" />
      <circle cx="17" cy="17" r="2" />
    </svg>
  );
}


interface DollarSignIconProps {
  className?: string; // You can include other props if needed
}

function DollarSignIcon(props: DollarSignIconProps) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <line x1="12" x2="12" y1="2" y2="22" />
      <path d="M17 5H9.5a3.5 3.5 0 0 0 0 7h5a3.5 3.5 0 0 1 0 7H6" />
    </svg>
  );
}
