/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/g5fFGcm6w1p
 */
import Link from "next/link"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"

export function signup() {
  return (
    <div className="flex flex-col h-screen font-sans bg-[#ffffff] text-[#000000]">
      <header className="flex items-center h-16 px-4 border-b shrink-0">
        <nav className="flex flex-row items-center justify-between w-full gap-6 text-lg font-medium md:gap-5 md:text-sm lg:gap-6">
          <Link className="flex items-center gap-2 text-lg font-semibold md:text-base" href="#">
            <Package2Icon className="w-6 h-6" />
            <span>Troulette</span>
          </Link>
          <div className="flex items-center gap-4">
            <Button className="rounded-full" size="icon" variant="ghost">
              <UserIcon className="w-4 h-4" />
              <span className="sr-only">Profile</span>
            </Button>
          </div>
        </nav>
      </header>
      <main className="flex flex-1 flex-col gap-4 md:gap-8 md:p-10">
        <div className="flex flex-row gap-4 justify-center">
          <form className="flex-1 sm:flex-initial">
            <div className="flex flex-row gap-4">
              <div className="relative">
                <label className="block text-sm font-medium text-gray-700">First Name:</label>
                <Input className="w-[300px]" placeholder="Enter your first name..." required type="text" />
              </div>
              <div className="relative">
                <label className="block text-sm font-medium text-gray-700">Last Name:</label>
                <Input className="w-[300px]" placeholder="Enter your last name..." required type="text" />
              </div>
            </div>
            <div className="flex flex-row gap-4">
              <div className="relative">
                <label className="block text-sm font-medium text-gray-700">Email Address:</label>
                <Input className="w-[300px]" placeholder="Enter your email address..." required type="email" />
              </div>
              <div className="relative">
                <label className="block text-sm font-medium text-gray-700">Phone Number:</label>
                <Input className="w-[300px]" placeholder="Enter your phone number..." required type="tel" />
              </div>
            </div>
            <div className="relative">
              <label className="block text-sm font-medium text-gray-700">Address:</label>
              <Input className="w-[617px]" placeholder="Enter your address..." required type="text" />
            </div>
            <div className="flex flex-row gap-4">
              <div className="relative">
                <label className="block text-sm font-medium text-gray-700">City:</label>
                <Input className="w-[195px]" placeholder="Enter your city..." required type="text" />
              </div>
              <div className="relative">
                <label className="block text-sm font-medium text-gray-700">State:</label>
                <Input className="w-[195px]" placeholder="Enter your state..." required type="text" />
              </div>
              <div className="relative">
                <label className="block text-sm font-medium text-gray-700">Zip Code:</label>
                <Input className="w-[195px]" placeholder="Enter your zip code..." required type="text" />
              </div>
            </div>
            <div className="relative">
              <label className="block text-sm font-medium text-gray-700">Credit Card Number:</label>
              <Input className="w-[617px]" placeholder="Enter your credit card number..." required type="text" />
            </div>
            <div className="flex flex-row gap-4">
              <div className="relative">
                <label className="block text-sm font-medium text-gray-700">Expiration:</label>
                <Input className="w-[300px]" placeholder="MM/YY" required type="text" />
              </div>
              <div className="relative">
                <label className="block text-sm font-medium text-gray-700">CVV:</label>
                <Input className="w-[300px]" placeholder="Enter your CVV..." required type="text" />
              </div>
            </div>
          </form>
        </div>
        <p className="text-center text-gray-600 mt-4 text-sm w-[600px] mx-auto overflow-hidden h-[2.5em]">
          Your Troulette Personal Plan will automatically renew annually, 12 months from the signup date, unless a
          cancellation is requested at least 14 days before the renewal date.
        </p>
        <Button className="self-center border border-gray-300 bg-[#ed4264] text-[#ffffff] py-8 px-8 text-lg mt-4">
          Sign Up
        </Button>
      </main>
      <footer className="flex items-center justify-center h-16 px-4 border-t text-sm text-gray-500 dark:text-gray-400">
        <span>© 2024 Troulette. All rights reserved. | </span>
        <Link className="ml-2" href="#">
          Privacy Policy
        </Link>
        <span className="mx-2">|</span>
        <Link className="mr-2" href="#">
          Terms of Service
        </Link>
      </footer>
    </div>
  )
}


function Package2Icon(props: React.SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M3 9h18v10a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V9Z" />
      <path d="m3 9 2.45-4.9A2 2 0 0 1 7.24 3h9.52a2 2 0 0 1 1.8 1.1L21 9" />
      <path d="M12 3v6" />
    </svg>
  );
}


function UserIcon(props: React.SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M19 21v-2a4 4 0 0 0-4-4H9a4 4 0 0 0-4 4v2" />
      <circle cx="12" cy="7" r="4" />
    </svg>
  );
}